ARG ELASTIC_VERSION

# https://www.docker.elastic.co/
FROM docker.elastic.co/logstash/logstash-oss:7.8.1

# Add your logstash plugins setup here
# Example: RUN logstash-plugin install logstash-filter-json
